# ---
# - name: update all nodes and set hostnames
#   hosts: '*'

#   vars_files:
#     - ../vars/vault.yaml
  
#   ## Make sure machines are up to date
#   pre_tasks:
#     - name: update ubuntu
#       become: true
#       become_method: sudo
#       ansible.builtin.apt:
#         name: "*"
#         state: latest

  # tasks:
  #   - name: Setup master node
  #     include_tasks: tasks/k3s_master.yaml
---
- name: Setup Master Nodes
  hosts: 'masters'

  vars_files:
    - ../vars/vault.yaml

  tasks:
    - name: Setup master node
      include_tasks: tasks/k3s_master.yaml