# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
UBUNTU_IMAGE = "ubuntu/focal64"
Vagrant.configure("2") do |config|

    ################################
    ###### Ansible Controller ######
    ################################
    config.vm.define "controller" do |subconfig|
        subconfig.vm.box = UBUNTU_IMAGE
        subconfig.vm.hostname = "controller"
        subconfig.vm.network :private_network, ip: "10.0.0.10"
        subconfig.vm.synced_folder "./ansible", "/home/vagrant"
        subconfig.vm.provision :hosts, :sync_hosts => true
        subconfig.vm.provision "shell", inline: <<-EOC
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt update
            sudo apt install --yes ansible sshpass
        EOC
    end

    ################################
    ####### k3s Master Nodes #######
    ################################
    config.vm.define "k3s-master-1" do |subconfig|
        subconfig.vm.box = UBUNTU_IMAGE
        subconfig.vm.hostname = "k3s-master-1"
        subconfig.vm.network :private_network, ip: "10.0.0.11"
        subconfig.vm.provision :hosts, :sync_hosts => true
        subconfig.vm.provision "shell", inline: <<-EOC
            echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNFtGxJc/hjlhHoqNX/VI60nSpd2VrLMKRKerKDHAatRQ8tHpX9M5BLzpUggGVqZRXYhzcinemYZ98uatLF0VFH+MkzZCLqOFynbAz3hecs31DZfXz9sRc8o6ndHR9RVMYzi9/VzjgLCmGdzq6OtR5BTcf4kxpWf13IXwbyv0eH2eUYKg78rLgDO4px6G43I15tjEXu7+lotRyldqjOmfeDWwW+qWVbTYGF43Bs8Flkpz3FEBnEicYXBHwIvg3MN61vAkGzFSQ8Or9Cee9Vnzogv09SSxu5c2V+LCSXbVLvkvJQqjLVZD+38j1Hs7Z/qwL+fcx129jzb7MyPKFGOIyD/efrRDCjJ8D2Z0YJMmtSMMx/D+lndK+Z20CQb/KR90DO2+Voehx/f+hmKzaUEPmI1XB8V37Y+bGhVSDPur/1LxnNhpVXqyWW7asx4+iYy/zu3LSIv15NmdTr7pgxwe6UgPv/E3n9hqMn0mpj0Wsn2HWxdZ3F6etqRxC5scDDbJXQBslzTEhL5E+PuPMBGMn8xOVl8Tg9aUVzGpJsK7Oa/EvXqClDogtfarSfzJWTMYwqOkJsnplR6oXh6aQWbPrUmjKmipxsGNq2FNxo9f57pGt0qLEWHU5CvwG8GqY3duUVqGrc6ZQSaQrHSJJo0eb6uqI7bGrOepJljw/k7WcVQ== develeap@develeaps-MacBook-Pro.local
            " >> /home/vagrant/.ssh/authorized_keys
            sudo sed -i -e "\\,PasswordAuthentication no, s,PasswordAuthentication no,PasswordAuthentication yes,g" /etc/ssh/sshd_config
            sudo service ssh restart
        EOC
    end

    ################################
    ####### k3s Worker Nodes #######
    ################################
    (1..2).each do |i|     
        config.vm.define "k3s-worker-#{i}" do |subconfig|
            subconfig.vm.box = UBUNTU_IMAGE 
            subconfig.vm.hostname = "k3s-worker-#{i}"       
            subconfig.vm.network :private_network, ip: "10.0.0.#{i + 11}"     
            subconfig.vm.provision :hosts, :sync_hosts => true
            subconfig.vm.provision "shell", inline: <<-EOC
                echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDNFtGxJc/hjlhHoqNX/VI60nSpd2VrLMKRKerKDHAatRQ8tHpX9M5BLzpUggGVqZRXYhzcinemYZ98uatLF0VFH+MkzZCLqOFynbAz3hecs31DZfXz9sRc8o6ndHR9RVMYzi9/VzjgLCmGdzq6OtR5BTcf4kxpWf13IXwbyv0eH2eUYKg78rLgDO4px6G43I15tjEXu7+lotRyldqjOmfeDWwW+qWVbTYGF43Bs8Flkpz3FEBnEicYXBHwIvg3MN61vAkGzFSQ8Or9Cee9Vnzogv09SSxu5c2V+LCSXbVLvkvJQqjLVZD+38j1Hs7Z/qwL+fcx129jzb7MyPKFGOIyD/efrRDCjJ8D2Z0YJMmtSMMx/D+lndK+Z20CQb/KR90DO2+Voehx/f+hmKzaUEPmI1XB8V37Y+bGhVSDPur/1LxnNhpVXqyWW7asx4+iYy/zu3LSIv15NmdTr7pgxwe6UgPv/E3n9hqMn0mpj0Wsn2HWxdZ3F6etqRxC5scDDbJXQBslzTEhL5E+PuPMBGMn8xOVl8Tg9aUVzGpJsK7Oa/EvXqClDogtfarSfzJWTMYwqOkJsnplR6oXh6aQWbPrUmjKmipxsGNq2FNxo9f57pGt0qLEWHU5CvwG8GqY3duUVqGrc6ZQSaQrHSJJo0eb6uqI7bGrOepJljw/k7WcVQ== develeap@develeaps-MacBook-Pro.local
                " >> /home/vagrant/.ssh/authorized_keys
                sudo sed -i -e "\\,PasswordAuthentication no, s,PasswordAuthentication no,PasswordAuthentication yes,g" /etc/ssh/sshd_config
                sudo service ssh restart
            EOC
        end
    end
end