# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
UBUNTU_IMAGE = "ubuntu/focal64"
Vagrant.configure("2") do |config|

    ################################
    ###### Ansible Controller ######
    ################################
    config.vm.define "controller" do |subconfig|
        subconfig.vm.box = UBUNTU_IMAGE
        subconfig.vm.hostname = "controller"
        subconfig.vm.network :private_network, ip: "10.0.0.10"
        subconfig.vm.provision :hosts, :sync_hosts => true

        ## Setup ssh keys
        config.ssh.insert_key = false
        config.ssh.private_key_path = ["/Users/develeap/Desktop/Lior/turningpi2-k3s/lab/.ssh/ansible", "~/.vagrant.d/insecure_private_key"]
        config.vm.provision "file", source: "/Users/develeap/Desktop/Lior/turningpi2-k3s/lab/.ssh/ansible", destination: "/home/vagrant/.ssh/ansible"
        config.vm.provision "file", source: "/Users/develeap/Desktop/Lior/turningpi2-k3s/lab/.ssh/ansible.pub", destination: "/home/vagrant/.ssh/authorized_keys"
        
        ## Install ansible and passthrough ssh
        subconfig.vm.provision "shell", inline: <<-EOC
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt update
            sudo apt install --yes ansible sshpass tree python3-pip
        EOC

        ## Sync the ansible folder with the controller
        config.vm.synced_folder "./ansible", "/home/vagrant/ansible", disabled: false
    end

    ################################
    ####### k3s Master Nodes #######
    ################################
    (1..2).each do |i|     
      config.vm.define "k3s-master-0#{i}" do |subconfig|
          subconfig.vm.box = UBUNTU_IMAGE
          subconfig.vm.hostname = "k3s-master-#{i}"
          subconfig.vm.network :private_network, ip: "10.0.0.#{i + 10}"
          subconfig.vm.provision :hosts, :sync_hosts => true

          ## Setup ssh keys
          config.vm.provision "file", source: "/Users/develeap/Desktop/Lior/turningpi2-k3s/lab/.ssh/ansible.pub", destination: "/home/vagrant/.ssh/authorized_keys"
      end
    end

    ################################
    ####### k3s Worker Nodes #######
    ################################
    (1..3).each do |i|     
        config.vm.define "k3s-worker-0#{i}" do |subconfig|
            subconfig.vm.box = UBUNTU_IMAGE 
            subconfig.vm.hostname = "k3s-worker-0#{i}"       
            subconfig.vm.network :private_network, ip: "10.0.0.#{i + 12}"     
            subconfig.vm.provision :hosts, :sync_hosts => true
            
            ## Setup ssh keys
            config.vm.provision "file", source: "/Users/develeap/Desktop/Lior/turningpi2-k3s/lab/.ssh/ansible.pub", destination: "/home/vagrant/.ssh/authorized_keys"            
        end
    end
end
