- name: Check for k3s command
  command: which k3sup 
  register: installed
  no_log: yes
  ignore_errors: yes

- name: Fetch k3s installation script
  ansible.builtin.get_url: 
    url: https://get.k3sup.dev
    dest: /tmp/install.sh
    mode: "u+rwx"
  when: installed.rc != 0
  register: download

- name: Execute the k3s install script
  become: true
  shell: /tmp/install.sh
  when: installed.rc != 0

- name: Remove the install.sh
  file: 
    path: /tmp/install.sh 
    state: absent
  when: installed.rc != 0

# - name: Sudo Install k3sup /usr/local/bin
#   command: sudo install $HOME/ansible/k3sup /usr/local/bin/k3sup 
#   when: installed.rc != 0
