- name: Check for k3s command
  command: command -v k3s 
  register: installed
  no_log: false
  ignore_errors: yes

- name: Fetch k3s installation script
  ansible.builtin.uri: 
    url: https://get.k3sup.dev
    dest: /tmp/install.sh
    mode: "u+rwx"
  when: installed.rc != 0
  register: download

- name: Execute the k3s install script
  become: true
  shell: /tmp/install.sh

- name: Remove the install.sh
  file: 
    path: /tmp/install.sh 
    state: absent

- name: Sudo Install k3sup /usr/local/bin
  command: sudo install $HOME/ansible/k3sup /usr/local/bin/k3sup 

- name: Check for kubectl command
  command: command -v kubectl 
  register: installed
  no_log: false
  ignore_errors: yes

- name: Fetch kubectl latest stable version
  ansible.builtin.uri: 
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
    follow_redirects: yes
  when: installed.rc != 0
  register: version
- debug:
    var: version.content

- name: Fetch kubectl installation script
  ansible.builtin.uri: 
    url: 'https://dl.k8s.io/release/{{ version.content }}/bin/linux/amd64/kubectl'
    dest: /tmp/kubectl
  when: installed.rc != 0
  register: download

- name: Sudo Install kubectl /usr/local/bin
  command: sudo install --owner root --group root --mode 0755 /tmp/kubectl /usr/local/bin/kubectl 

- name: Remove /tmp/kubectl
  file: 
    path: /tmp/kubectl 
    state: absent
# - name: Installing Zsh
#   become: true
#   ansible.builtin.apt: 
#     name: zsh
#     state: latest
#
# - name: Execute the k3s install script
#   become: true
#   shell: /tmp/install.sh \
#     --write-kubeconfig-mode 644 \
#     --disable servicelb \
#     --token "{{ k3s_token }}" \
#     --node-ip "{{ response.content }}" \
#     --disable-cloud-controller \
#     --disable local-storage
#   when: download.changed
#
# - name: Remove the install.sh
#   file: 
#     path: /tmp/install.sh 
#     state: absent

# - name: Run k3s installer on the master node
#   ansible.builtin.shell:
#     cmd: sh -s \
#       --write-kubeconfig-mode 644 \
#       --disable servicelb \
#       --token "{{ k3s_token }}" \
#       --node-ip "{{ response.content }}" \
#       --disable-cloud-controller \
#       --disable local-storage
#     stdin: "{{ k3s_installer.content }}"

# - name: Label a master node
#   ansible.builtin.shell:
#     cmd: kubectl label nodes {{ hostname }} kubernetes.io/role=master &&\
#       kubectl label nodes cube01 node-type=master
